title = "Miller Larson"
baseURL = "https://resume.millerlarson.net/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Rathdrum, ID"
email = "miller.larson@gmail.com"
favicon = "/favicon.ico"
firstName = "Miller"
lastName = "Larson"
phone = "1-208-555-5555"
profileImage = "img/staff_portrait.jpg"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = false
showPublications = false
showQr = true
showSkills = true

[params.google]

# [params.google.analytics]
# trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/millerlarson/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/millerlarson/"
name = "GitHub"

#[[params.handles]]
#link = "https://hub.docker.com/u/millerlarson"
#name = "Docker"

[[params.handles]]
link = "https://keybase.io/miller"
name = "Keybase"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
